name: BookShelf
main: me.Pew446.BookShelf.BookShelf
version: 3.6
description: Allows players to store books in bookshelves.
author: Pew446
dev-url: http://dev.bukkit.org/server-mods/BookShelf
softdepend: [Vault,Towny,LWC,WorldEdit,WorldGuard]
commands:
   bsunlimited:
      description: Sets target bookshelf to never run out of books.
      usage: /<command>
      aliases: ['bsu']
      permission-message: You don't have permission for that command!
   bstoggle:
      description: Toggles target bookshelf enabled/disabled, or all shelves with the same specified name.
      usage: /<command> [shelf name]
      aliases: ['bst']
      permission-message: You don't have permission for that command!
   bsreload:
      description: Reloads the BookShelf configuration file.
      usage: /<command>
      aliases: ['bsr']
      permission: bookshelf.reload
      permission-message: You don't have permission for that command!
   bsshop:
      description: Toggles target bookshelf as shop or normal.
      usage: /<command> price
      aliases: ['bss']
      permission-message: You don't have permission for that command!
   bsname:
      description: Changes name of target bookshelf.
      usage: /<command> name
      aliases: ['bsn']
      permission-message: You don't have permission for that command!
   bstowny:
      description: Multiple commands for Towny support.
      usage: /<command>
      permission: bookshelf.towny
      permission-message: You don't have permission for that command!
   bsdonate:
      description: Sets target bookshelf to be a donation shelf.
      usage: /<command>
      aliases: ['bsd']
      permission-message: You don't have permission for that command!
   bsedit:
      description: Enables edit mode, allowing the owner(s) to modify contents of a shelf.
      usage: /<command>
      aliases: ['bse']
      permission-message: You don't have permission for that command!
   bssetowners:
      description: Sets the owners of the target bookshelf.
      usage: /<command> Owner1 [Owner2] [Owner3] ...
      permission-message: You don't have permission for that command!
   bsaddowners:
      description: Adds to the owners of the target bookshelf.
      usage: /<command> Owner1 [Owner2] [Owner3] ...
      permission-message: You don't have permission for that command!
   bsremoveowners:
      description: Removes from the owners of the target bookshelf.
      usage: /<command> Owner1 [Owner2] [Owner3] ...
      permission-message: You don't have permission for that command!
   bsgetowners:
      description: Gets the owners of the target bookshelf.
      usage: /<command>
      permission-message: You don't have permission for that command!
permissions:
    bookshelf.*:
        description: Gives all permissions of BookShelf.
        children:
            bookshelf.unlimited: true
            bookshelf.toggle: true
            bookshelf.reload: true
            bookshelf.shop: true
            bookshelf.name: true
            bookshelf.towny: true
            bookshelf.donate: true
            bookshelf.setowners: true
            bookshelf.addowners: true
            bookshelf.removeowners: true
            bookshelf.getowners: true
            bookshelf.openshelf: true
            bookshelf.book: true
            bookshelf.baq: true
            bookshelf.signed: true
            bookshelf.maps: true
            bookshelf.enchanted_book: true
            bookshelf.records: true
            bookshelf.paper: true
            
    bookshelf.unlimited:
        description: Allows player to make bookshelves never run out of books.
        default: op
    bookshelf.toggle:
        description: Allows player to toggle shelves enabled/disabled.
        default: true
    bookshelf.reload:
        description: Allows player to reload the config.
        default: op
    bookshelf.shop:
        description: Allows player to create shop shelves.
        default: true
    bookshelf.name:
        description: Allows player to change names of bookshelves.
        default: true
    bookshelf.towny:
        description: Allows players to use /bstowny command for Towny.
        default: true
    bookshelf.donate:
        description: Allows player to turn bookshelves into a donation shelf.
        default: true
    bookshelf.setowners:
        description: Allows player to set the owners of any shelf.
        default: true
    bookshelf.addowners:
        description: Allows player to add owners to any shelf.
        default: true
    bookshelf.removeowners:
        description: Allows player to remove owners from any shelf.
        default: true
    bookshelf.getowners:
        description: Allows player to get the owners of any shelf.
        default: true
    bookshelf.openshelf:
        description: Allows player to open any shelf.
        default: op
    bookshelf.book:
        description: Allows player to add plain books to shelves.
        default: true
    bookshelf.baq:
        description: Allows player to add book and quills to shelves.
        default: true
    bookshelf.signed:
        description: Allows player to add signed books to shelves.
        default: true
    bookshelf.maps:
        description: Allows player to add maps to shelves.
        default: true
    bookshelf.enchanted_book:
        description: Allows player to add enchanted books to shelves.
        default: true
    bookshelf.records:
        description: Allows player to add records to shelves.
        default: true
    bookshelf.paper:
        description: Allows player to add paper to shelves.
        default: true
    